#ifndef PAYLOADERBESSD_GLOBAL_H
#define PAYLOADERBESSD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PAYLOADERBESSD_LIBRARY)
#  define PAYLOADERBESSD_EXPORT Q_DECL_EXPORT
#else
#  define PAYLOADERBESSD_EXPORT Q_DECL_IMPORT
#endif

#endif // PAYLOADERBESSD_GLOBAL_H
