#ifndef PAYLOADMILESIGHT_GLOBAL_H
#define PAYLOADMILESIGHT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PAYLOADMILESIGHT_LIBRARY)
#  define PAYLOADMILESIGHT_EXPORT Q_DECL_EXPORT
#else
#  define PAYLOADMILESIGHT_EXPORT Q_DECL_IMPORT
#endif

#endif // PAYLOADMILESIGHT_GLOBAL_H
